[workspace]
resolver = "3"
members = ["elysia-os-lib","kernel", "test-init"]

[package]
name = "elysia-os-runner"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
ovmf-prebuilt = "0.2"

[build-dependencies]
bootloader = "0.11"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }

[patch.crates-io]
test-init = { path = "test-init", artifact = "bin", target = "x86_64-unknown-none"}

