[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
x86_64 = "0.15.4"
xmas-elf = "0.10.0"
acpi = "6.0.1"
bootloader_api = "0.11"
volatile = "0.6.1"
elfloader = "0.16.0"
spin = "0.5.2"
paste = "1.0.15"
linked_list_allocator = "0.9.0"
pc-keyboard = "0.7.0"
const-random = "0.1.18"
uart_16550 = "0.2.0"
qemu-exit = "3.0.2"
pic8259 = "0.11.0"
spleen-font = { version = "0.2", features = ["all"] }

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[dependencies.num_enum]
version = "0.7.5"
default-features = false

[[test]]
name = "stack_overflow"
harness = false

[dependencies.crossbeam-queue]
version = "0.3.11"
default-features = false
features = ["alloc"]
[dependencies.conquer-once]
version = "0.2.0"
default-features = false
[dependencies.futures-util]
version = "0.3.4"
default-features = false
features = ["alloc"]
